[tool.ruff]
line-length = 120
select = ["E", "W", "F", "I", "D", "N", "S", "A", "B"]
ignore = [
    "F821",
    "F841",
    "D100",
    "D107",
    "D211",
    "D212",
    "S301",
    "S311",
    "S603",
    "S605",
    "S607",
    "B008",
    "B028",
    "B905", # `zip()` without an explicit `strict=` parameter
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.codespell]
skip = "*.pdf,*.ipynb"
